DROP TABLE IF EXISTS endpoint_hit CASCADE;

CREATE TABLE IF NOT EXISTS endpoint_hit (
endpoint_hit_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
app VARCHAR,
uri VARCHAR,
ip VARCHAR,
time_stamp TIMESTAMP
);


