DROP TABLE IF EXISTS endpoint_hit CASCADE;

CREATE TABLE IF NOT EXISTS endpoint_hit (
endpoint_hit_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
app VARCHAR NOT NULL,
uri VARCHAR NOT NULL,
ip VARCHAR NOT NULL,
time_stamp TIMESTAMP NOT NULL
);


