version: '3.1'
services:
  stats-server:
    build: ./stat/service
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stat
      - POSTGRES_USER=ewm-user
      - POSTGRES_PASSWORD=123

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stat
      - POSTGRES_USER=ewm-user
      - POSTGRES_PASSWORD=123

  ewm-service:
    build: ./main
    ports:
      - "8080:8080"
    container_name: main-service
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
      - POSTGRES_USER=ewm-user
      - POSTGRES_PASSWORD=123
      - STAT_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=ewm-user
      - POSTGRES_PASSWORD=123
